---

- import_tasks: 10_install.yml
- import_tasks: 15_glusterfs.yml
- import_tasks: 20_configure.yml
- import_tasks: 25_consul.yml

- name: Force all notified handlers
  ansible.builtin.meta: flush_handlers

- name: Ensure daemon is started and will start on boot
  become: true
  ansible.builtin.systemd:
    name: nomad
    state: started
    enabled: true
