---

all:
  hosts:
    iddqd-uk-node-1:
      ansible_host: &node-1-ip 192.168.56.116
      private_ip: *node-1-ip
      consul_retry_join_hosts: [iddqd-uk-node-2]
      nomad_retry_join_hosts: [iddqd-uk-node-2]
      glusterfs_join_hosts: [iddqd-uk-node-2]
    iddqd-uk-node-2:
      ansible_host: &node-2-ip 192.168.56.117
      private_ip: *node-2-ip
      consul_retry_join_hosts: [iddqd-uk-node-1]
      nomad_retry_join_hosts: [iddqd-uk-node-1]
      glusterfs_join_hosts: [iddqd-uk-node-1]
