---

all:
  hosts:
    iddqd-uk-master-1:
      ansible_host: 192.168.56.114
      private_ip: 192.168.56.114
    iddqd-uk-worker-1:
      ansible_host: 192.168.56.113
      private_ip: 192.168.56.113

  children:
    masters:
      hosts:
        iddqd-uk-master-1: {}
    workers:
      hosts:
        iddqd-uk-worker-1: {}
