# Used tool: https://github.com/jtesta/ssh-audit
---

- name: Disable password authentication
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
  notify: [restart ssh]

- name: Set HostKeyAlgorithms
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^HostKeyAlgorithms'
    line: "HostKeyAlgorithms {{ names | join(',') }}"
  vars:
    names:
      - ssh-ed25519-cert-v01@openssh.com
      - ssh-rsa-cert-v01@openssh.com
      - ssh-ed25519
      - rsa-sha2-256
      - rsa-sha2-512
  notify: [restart ssh]

- name: Set KexAlgorithms
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^KexAlgorithms'
    line: "KexAlgorithms {{ names | join(',') }}"
  vars:
    names:
      - curve25519-sha256
      - curve25519-sha256@libssh.org
      - diffie-hellman-group18-sha512
      - diffie-hellman-group14-sha256
      - diffie-hellman-group16-sha512
      - diffie-hellman-group-exchange-sha256
  notify: [restart ssh]

- name: Set Ciphers
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^Ciphers'
    line: "Ciphers {{ names | join(',') }}"
  vars:
    names:
      - chacha20-poly1305@openssh.com
      - aes256-gcm@openssh.com
      - aes128-gcm@openssh.com
      - aes256-ctr
      - aes192-ctr
      - aes128-ctr
  notify: [restart ssh]

- name: Set MACs
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^MACs'
    line: "MACs {{ names | join(',') }}"
  vars:
    names:
      - hmac-sha2-512-etm@openssh.com
      - hmac-sha2-256-etm@openssh.com
      - umac-128-etm@openssh.com
  notify: [restart ssh]
