---

- name: Set TimeZone
  become: true
  block:
    - name: Install tzdata
      ansible.builtin.apt:
        name: tzdata
        state: present
        cache_valid_time: 21600 # in seconds, 60 × 60 × 6 = 6 hours
        update_cache: true

    - name: Set localtime UTC
      ansible.builtin.file:
        path: /etc/localtime
        src: /usr/share/zoneinfo/UTC
        state: link
        group: root
        owner: root
        mode: 0644
